In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [28]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/materias/materias.csv

In [27]:
import pandas as pd

In [69]:
datos= pd.read_csv('../input/materias/materias.csv')

In [30]:
datos.head(1)

  Alumno;Curso;Materias Previas;Materias Desaprobadas
0                                         Ana;5A;2;1

In [34]:
datos.tail(1)

  Alumno;Curso;Materias Previas;Materias Desaprobadas
8                                     Micaela;6B;3;2

In [74]:
df1 = pd.DataFrame(datos)

In [5]:
datos_filtrados= df1["Materias Desaprobadas"]= 0

NameError: name 'df1' is not defined